### ISSUE TITLE
Compatibility with / Support of Ubuntu 24.04

### ISSUE THREAD

**Issue by MaWel8** [eclipse-adore/adore_ROS1#71]
Dear ADORe Team,

we are currently setting up a machine to use ADORe.
In your documentation you recommend Ubuntu 20.04 or 22.04.
Since Ubuntu 24.04 released some days ago, we are thinking of using that version to keep the maintenance overhead small.

-> 
Do you have already experience using 24.04 together with ADORe?
Are you planning internally to upgrade to 24.04 as well, or will you stay on Ubuntu 22.04 and not support 24.04 for now?

Thanks a lot & Best regards,
MaWel

**Comment by tlobig** [comment]
Dear Marc,thank you for your question. In general there shouldn't be any obstacles using ADORe with newer Ubuntu versions, since it's dockerized. Alas we have not yet tested it with Ubuntu 24.04Let us know if you run into issues.Kind regards Thomas Lobig Am 30.04.2024 12:48 schrieb Marc Wellstein ***@***.***>:
Dear ADORe Team,
we are currently setting up a machine to use ADORe.
In your documentation you recommend Ubuntu 20.04 or 22.04.
Since Ubuntu 24.04 released some days ago, we are thinking of using that version to keep the maintenance overhead small.
->
Do you have already experience using 24.04 together with ADORe?
Are you planning internally to upgrade to 24.04 as well, or will you stay on Ubuntu 22.04 and not support 24.04 for now?
Thanks a lot & Best regards,
MaWel

**Comment by akoerner1** [comment]
@MaWel8 Since your message I was able to test everything under ubuntu 24.04.  There are no intimidate issues, you should be able to use 24.04 with no problems.

**Comment by MaWel8** [comment]
Dear Andrew & Thomas,

Great to hear that.
Thanks a lot for testing!

Best regards,
Marc

**Comment by akoerner1** [comment]
@MaWel8 If you choose to use the setup script then make sure you have the latest version:
https://github.com/DLR-TS/adore_tools/blob/50d45f6dc51c9424db6ca8e5197430f5a2b3152f/tools/adore_setup.sh#L12

I added 24.04 as a valid version number.
